New sozluk term: JWT
kamp-us/pano pull request #497
Opened 2023-07-06 00:32 UTC by MuhammedDemirell

add-jwt-sozluk-term

# Description

Please describe your changes. Be descriptive enough to reduce churn for review process.

### Checklist

- [ ] discord username: `username#0001`
- [ ] Closes #<issue-number>
- [ ] PR must be created for an issue from issues under "In progress" column from [our project board](https://github.com/orgs/kamp-us/projects/2/views/1).
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules, and should include the app/package/service name in the title. For example, a title like "docs(@kampus-apps/pano): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] I ran `npx turbo run` at the root of the repository, and build was successful.
- [ ] I installed the npm packages using `npm install --save-exact <package>` so my package is pinned to a specific npm version. Leave empty if no package was installed. Leave empty if no package was installed with this PR.

### How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

2023-07-06 01:12 UTC, usirin commented on packages/sozluk-content/terms/jwt.mdx
> +JSON Web Token'ın kısaltmasıdır ve web uygulamaları arasında güvenli iletişimi sağlamak için kullanılan bir standarttır. Bu standart, JSON formatında veri paylaşımını ve dijital imzayı birleştirerek,
"JSON Web Token'ın kisaltmasidir" kismini burada kullanmak yerine `title` kismini `JWT - JSON Web Token` olarak degistirelim.

2023-07-06 01:12 UTC, usirin requested changes
ufak bir not biraktim, cok tesekkurler.

2023-07-07 06:33 UTC, Ketcap commented
> add-jwt-sozluk-term
> 
> # Description
> Please describe your changes. Be descriptive enough to reduce churn for review process.
> 
> ### Checklist
> * [ ]  discord username: `username#0001`
> * [ ]  Closes #
> * [ ]  PR must be created for an issue from issues under "In progress" column from [our project board](https://github.com/orgs/kamp-us/projects/2/views/1).
> * [ ]  A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules, and should include the app/package/service name in the title. For example, a title like "docs(@kampus-apps/pano): Add README.md" can be used.
> * [ ]  Related file selection: Only relevant files should be touched and no other files should be affected.
> * [ ]  I ran `npx turbo run` at the root of the repository, and build was successful.
> * [ ]  I installed the npm packages using `npm install --save-exact <package>` so my package is pinned to a specific npm version. Leave empty if no package was installed. Leave empty if no package was installed with this PR.
> 
> ### How were these changes tested?
> Please describe the tests you did to test the changes you made. Please also specify your test configuration.

İlk defa PR açtığını görüyorum süpersin 👌
Senden ricam o todo listte PRın için geçerli yerleri doldurman. Özellikle discord username 😄

2023-07-16 09:26 UTC, Ketcap approved these changes

2023-07-16 09:29 UTC, merged