feat(pano): single post page
kamp-us/pano pull request #511
Opened 2023-07-09 09:07 UTC by FurkanGM

#510 implementation

2023-07-16 09:35 UTC, Ketcap requested changes
@FurkanGM PR icin tesekkurler 🤌 testlerini ekleyelim eksik kalmasin

2023-07-16 09:35 UTC, Ketcap commented on db/prisma/schema.prisma
> +  username      String   @unique
username next-auth'da optional olarak verildigi icin oyle eklenmisti. Bu sonradan sorun cikarir optional olarak birakalim PR'in scope'una ait de degil hem

2023-07-16 09:35 UTC, Ketcap commented on apps/gql/loaders/pano.ts
> +    const result = await findManyCursorConnection(
bu satir icin diger implementasyonlara bakar misin. extra paket direkt eklemek ilk secenek olmasin.

2023-07-16 09:35 UTC, Ketcap commented on apps/gql/loaders/pano.ts
> +    const result = await findManyCursorConnection(
Pagination icin fonksiyonlar var su an onlara bir bak https://github.com/kamp-us/monorepo/blob/073b822cf089c9713785e8db2fd69233cbc43a7a/apps/gql/features/relay/pagination.ts#L36

2023-07-27 08:15 UTC, usirin commented
Closing this as now we implemented all the functionality that exists here with several other pull requests, you can track the remaining progress from #510 

Thank you so much for making the initial work @FurkanGM it literally gave me the initial roadmap, and helped us figure out the problems early on in the process. This is a great example of creating a PR to start a work and let the rest of the team handle the remaining parts. Thank you for being an example to the community!

2023-07-27 08:15 UTC, closed without merging