sozluk-content/terms for Devops, Cloud, Http-Methods
kamp-us/pano pull request #538
Opened 2023-07-21 23:09 UTC by akselsaatci

# Description

Please describe your changes. Be descriptive enough to reduce churn for review process.

### Checklist

- [x] discord username: `akselsaatci`
- [x] Closes #525 (devops,cloud,http-methods)
- [x] PR must be created for an issue from issues under "In progress" column from [our project board](https://github.com/orgs/kamp-us/projects/2/views/1).
- [x] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules, and should include the app/package/service name in the title. For example, a title like "docs(@kampus-apps/pano): Add README.md" can be used.
- [x] Related file selection: Only relevant files should be touched and no other files should be affected.
- [x] I ran `npx turbo run` at the root of the repository, and build was successful.
- [x] I installed the npm packages using `npm install --save-exact <package>` so my package is pinned to a specific npm version. Leave empty if no package was installed. Leave empty if no package was installed with this PR.

### How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

### Sources
https://medium.com/devopsturkiye/devops-nedi%CC%87r-9f7e39b63b9c
https://aws.amazon.com/what-is-cloud-computing/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
and of course https://chat.openai.com/

2023-07-22 08:16 UTC, igdiaysu commented on packages/sozluk-content/terms/cloud.mdx
> +  - cloud services
```suggestion
  - cloud-computing
  - cloud-services
```

2023-07-22 08:17 UTC, igdiaysu commented on packages/sozluk-content/terms/devops.mdx
> +  - Pipeline
```suggestion
  - continuous-integration
  - continuous-deployment
  - deployment
  - pipeline
```

2023-07-22 08:20 UTC, igdiaysu commented on packages/sozluk-content/terms/http-methods.mdx
> +  - GET POST PUT DELETE PATCH HEAD OPTIONS CONNECT TRACE
```suggestion
  - http
  - get
  - post
  - put
  - delete
  - patch
  - head
  - options
  - connect
  - trace
```

2023-07-22 08:22 UTC, igdiaysu commented on packages/sozluk-content/terms/http-methods.mdx
> +Http metotları sunucu ile istemci arasında iletişim kurmak için kullanılan komutlardır. Http protokolü 9 adet metot tanımlamıştır. Bunlar : GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT ve TR
```suggestion
HTTP metotları sunucu ile istemci arasında iletişim kurmak için kullanılan komutlardır. HTTP protokolü 9 adet metot tanımlamıştır: GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT ve TRACE.  
```

2023-07-22 21:53 UTC, aecepoglu requested changes
Bir konumda yonelim eki hatali diye dusundum.

Bu dedigim ise degisim istegi degil, sadece dusuncemi paylasiyorum: Sozlukteki cumleler icin kelime sayisi ust limiti getirilmeli. cloud ve devops'un tanimlarini okurken cumlenin basini unuttum.

2023-07-22 21:53 UTC, aecepoglu commented on packages/sozluk-content/terms/cloud.mdx
> +Bulut bilişimleri fiziksel sunucuları satın almak, sahip olmak ve bakımını yapmak yerine bunları bir sağlayıcı tarafından ulaşmamızı sağlar. Kullanıma göre fiyatlandırılır. İhtiyaçlara göre ölçeklend
bunlari -> bunlara ?

2023-07-23 18:57 UTC, akselsaatci commented
> Bir konumda yonelim eki hatali diye dusundum.
> 
> Bu dedigim ise degisim istegi degil, sadece dusuncemi paylasiyorum: Sozlukteki cumleler icin kelime sayisi ust limiti getirilmeli. cloud ve devops'un tanimlarini okurken cumlenin basini unuttum.

2. dediğinizde haklı olabilirsiniz kısaltmaya çalışacağım

2023-07-25 13:38 UTC, Ketcap commented
@akselsaatci @igdiaysu Is there anything else needs to be resolved here ? If not we can just merge this.

2023-07-26 08:02 UTC, igdiaysu commented
> @akselsaatci @igdiaysu Is there anything else needs to be resolved here ? If not we can just merge this.

I think it can be merged . But i was not sure because of the above [dialog](https://github.com/kamp-us/monorepo/pull/538#issuecomment-1646932086)

2023-07-27 08:39 UTC, aecepoglu approved these changes

2023-07-27 12:12 UTC, Ketcap approved these changes

2023-07-27 15:52 UTC, merged