feat(@kampus/pano): Initial folder setup with next
kamp-us/pano pull request #541
Opened 2023-07-24 23:00 UTC by cansirin

This PR introduces initial folder setup and a couple components related with the routing. 

Details:

-

2023-07-24 23:42 UTC, usirin commented on apps/kampus/app/pano/features/post/PanoFilterLink.tsx
> +export function PanoFilterLink({ href, children }: { href: string; children: React.ReactNode }) {
let's convert this to a util & component that accepts the filter type (can be a string literal union), and returns an absolute url based on that.

2023-07-25 08:23 UTC, usirin requested changes
List of things we decided to do on stream:
- Use `/posts/....` for pages working with a list of posts
- Use `/post/....` for pages working with a single post
- Let's try to use

2023-07-25 23:20 UTC, usirin commented on apps/kampus/app/pano/features/post/PostSortFilters.tsx
> +export type PanoPostFilterType = (typeof filters)[number]["query"];
let's drive filters from the type we build, not the other way around.

2023-07-26 07:55 UTC, Ketcap approved these changes

2023-07-26 07:55 UTC, Ketcap commented on apps/kampus/app/pano/features/filter/utils.ts
> +};
not sure about this but we can figure out later. It's interesting dictionary to work with.

2023-07-26 08:13 UTC, usirin approved these changes
💯

2023-07-26 08:13 UTC, merged