used toast component
kamp-us/pano pull request #577
Opened 2023-07-30 21:49 UTC by muhammed-gumus

# Description

Please describe your changes. Be descriptive enough to reduce churn for review process.

### Checklist

- [ ] discord username: `username#0001`
- [ ] Closes #<issue-number>
- [ ] PR must be created for an issue from issues under "In progress" column from [our project board](https://github.com/orgs/kamp-us/projects/2/views/1).
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules, and should include the app/package/service name in the title. For example, a title like "docs(@kampus-apps/pano): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] I ran `npx turbo run` at the root of the repository, and build was successful.
- [ ] I installed the npm packages using `npm install --save-exact <package>` so my package is pinned to a specific npm version. Leave empty if no package was installed. Leave empty if no package was installed with this PR.

### How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

2023-08-01 21:12 UTC, Ketcap approved these changes

2023-08-02 05:27 UTC, cansirin commented on apps/kampus/app/layout.tsx
> +import { ThemeProvider, Toast } from "@kampus/ui-next";
```suggestion
import { ThemeProvider } from "@kampus/ui-next";
```

2023-08-02 05:29 UTC, cansirin commented on apps/kampus/app/pano/features/post-list/MoreOptions.tsx
> +              description: "link kopyalandı",
```suggestion
              description: "Post linki kopyalandı",
```

2023-08-02 05:31 UTC, cansirin commented on apps/kampus/app/pano/features/post-list/MoreOptions.tsx
> +          Adresi kopyala
```suggestion
          Linki kopyala
```

Hangi kelimeyi kullanmamiz gerektigine tam karar veremiyorum, var mi oneriniz? @usirin @Ketcap

2023-08-02 07:15 UTC, usirin commented on apps/kampus/app/pano/features/post-list/MoreOptions.tsx
> +          Adresi kopyala
Linki kopyala daha mantikli, let's go

2023-08-02 07:15 UTC, usirin commented on apps/kampus/app/pano/features/post-list/MoreOptions.tsx
> +              description: "link kopyalandı",
`Link kopyalandı` iyidir bence.

2023-08-03 19:14 UTC, Ketcap commented
If you can make sure to go through checklist I would merge it immediately :)

2023-08-04 21:49 UTC, usirin commented on apps/kampus/app/pano/features/post-list/MoreOptions.tsx
> +  //console.log(post, shareUrl);
let's remove this

2023-08-04 21:51 UTC, usirin requested changes
Things look pretty good, though we need to run prettier on the changed files. @cansirin can you assist?

2023-08-04 22:16 UTC, usirin approved these changes

2023-08-04 22:19 UTC, usirin commented on apps/kampus/app/pano/features/post-list/MoreOptions.tsx
> +  //console.log(post, shareUrl);
```suggestion
```

2023-08-06 22:57 UTC, cansirin approved these changes
LETS GOOOOOOOO!

2023-08-06 22:57 UTC, merged